default:
  image: node:20-alpine

tests:

  script:
    - npm ci --cache .npm --prefer-offline --loglevel notice
    - npm run test:ci
  cache:
    # Cache according to the branch/tag name
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
    - .npm/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
